### ISSUE TITLE
"No need for sudo" is misleading

### ISSUE THREAD

**Issue by njh** [node-red/linux-installers#10]
Hi,

I have been trying to install node-red as a 'system' user - with uid `node-red`, rather than my personal user.

When running as root, you get presented a message saying:
```
Root user detected. Typically install as a normal user. No need for sudo.

Are you really sure you want to install as root ? (y/N) ? 
```

But then when running as the user `node-red`, I get the message:

```
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for node-red: 
```

I think the message means you don't have to run `node-red` command with `sudo` but that isn't very clear.

**Comment by dceejay** [comment]
The first message is ours - advising that generally it's not a good idea to install as root...
The second is from debian the first time you do something using sudo - so not something we can change.

Apologies I'm not quite clear on what your question/suggestion is ?

**Comment by njh** [comment]
Hi Dave!

Sorry for not being clear.

When I first read the _"No need for sudo."_ message, I thought it meant that there was no need for `sudo` in order to perform the install. But I think what it actually means, is once it is installed the non-root user doesn't need sudo to run `node-red`.

My suggestion is to amend the message to something like:

```
Root user detected. Typically install as a normal user.
After installation there is no need for sudo to run node-red.

Are you really sure you want to install as root ? (y/N) ? 
```

nick.

**Comment by dceejay** [comment]
well I would argue if you are installing as root you then are expecting to run as root... it's more to alert the user to the fact they don't need to install as root (using sudo) - as the script can't tell the difference I think between being run as the user root or a user with sudo... If we could we could just exit instead of letting them do it wrong.

**Comment by knolleary** [comment]
Would it be clearer if the message said:

> You are running this script as the root user. Typical installs should be done as a regular user.
> If you are running this script using sudo, please cancel and rerun without sudo.
> If you know what you are doing as root, please continue.

**Comment by njh** [comment]
@knolleary sounds great, very clear 👍

**Comment by dceejay** [comment]
Have just found the $SUDO_USER variable... only set if running as sudo - so we can warn and fail instantly instead. (But if really are root and not using sudo it's not set so a real root user can install just fine...)

**Comment by dceejay** [comment]
check added to script
