### ISSUE TITLE
Install fails on AlmaLinux 8.4

### ISSUE THREAD

**Issue by andrewm659** [node-red/linux-installers#17]
Trying to install nodered on Almalinux and get the following error:

```
Doesn't seem to be running on RedHat, Centos, Fedora, or Oracle Linux, so quitting
```
I tried removing the symlink from /etc/centos-release to /etc/almalinux-release and recreating the files with the CentOS and or Red Hat release info.  Still didn't work.

Is this resolved in version 16?

**Comment by dceejay** [comment]
never heard of almalinux so never tested. Happy to consider a pull  request if anyone willing to work it out.

**Comment by andrewm659** [comment]
Alma Linux and Rocky Linux are the new stable clones of RedHat and or CentOS.

**Comment by dceejay** [comment]
If you grab the actual install script and edit line 67 to include the relevant release word - then what error do you get ?

**Comment by andrewm659** [comment]
dnf.

**Comment by andrewm659** [comment]
I made it look like this and it worked
```
versions='fedora"centos"rhel"ol"almalinux"rockylinux'
```

**Comment by dceejay** [comment]
did you also need to change line 103 so it picks the dnf path ?
