### ISSUE TITLE
Came across this today?  Looks like the install script needs a slight tweak?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [node-red/linux-installers#32]
Running Node-RED install for user pi at /home/pi on debian

This can take 20-30 minutes on the slower Pi versions - please wait.

  Stop Node-RED                       ✔
  Remove old version of Node-RED      ✔
  Remove old version of Node.js       ✔
  Install Node.js 16 LTS              ✔   v16.16.0   Npm 8.11.0
  Clean npm cache                     ✔
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
  Install Node-RED core               ✔   3.0.0
  Move global nodes to local          -
  Npm rebuild existing nodes          ✔
  Install extra Pi nodes              ✔
  Add shortcut commands               ✔
  Update systemd script               ✔

Any errors will be logged to   /var/log/nodered-install.log

All done.
You can now start Node-RED with the command  node-red-start
  or using the icon under   Menu / Programming / Node-RED
Then point your browser to localhost:1880 or http://{your_pi_ip-address}:1880

Started :  Mon 18 Jul 2022 08:47:19 PM UTC
Finished:  Mon 18 Jul 2022 08:54:06 PM UTC

You may want to run   node-red admin init
to configure your initial options and settings.

**Comment by knolleary** [comment]
What exactly are you reporting? What change are you suggesting?

**Comment by dceejay** [comment]
related to this - https://github.com/node-red/linux-installers/issues/31
we won't fix this for a while as a) we still support "old" npm and b) npm are fixing the regression / warning for a while
Eventually we will fix it - but having a warning for one group of users is better than the install failing for another group.

**Comment by Jibun-no-Kage** [comment]
Yeah, just could not find much about it via Google when I looked earlier today.  So was not sure if it was known.
