### ISSUE TITLE
script with no sudo

### ISSUE THREAD

**Issue by syswombat** [node-red/linux-installers#35]
hello
would be nice to have the script running without sudo 
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)

/dev/fd/63: Zeile 278: sudo: Kommando nicht gefunden.
/dev/fd/63: Zeile 281: sudo: Kommando nicht gefunden.
/dev/fd/63: Zeile 283: sudo: Kommando nicht gefunden.
/dev/fd/63: Zeile 284: sudo: Kommando nicht gefunden.
/dev/fd/63: Zeile 293: sudo: Kommando nicht gefunden.

**Comment by dceejay** [comment]
What operating system and version are you using ? How do you install applications as a normal user without using Suso to give you admin privileges ?

**Comment by dceejay** [comment]
We really don't recommend installing as root... but I have just uploaded a version of the script that hopefully may detect root and not call sudo...
