### ISSUE TITLE
Node-Red not fully installed

### ISSUE THREAD

**Issue by agentflippy5** [node-red/linux-installers#4]
I run the install script with this command:
`bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)`

It seemed to run successfully, but node-red will not start (see picture below)
![image](https://user-images.githubusercontent.com/8158058/75987800-89633980-5ebe-11ea-8815-3ab094f7114a.png)

I am running Ubuntu 18.04 on Windows Subsystem for Linux, and have installed build-essential

**Comment by knolleary** [comment]
Have you looked in the error log it highlights?

In general, we prefer to handle support type questions on the forum - https://discourse.nodered.org - where the wider community are able to help.

**Comment by dceejay** [comment]
should now be fixed with later patches
