### ISSUE TITLE
No an issure, but i have no clue.

### ISSUE THREAD

**Issue by Onshuis** [node-red/linux-installers#41]
I installed it with the bash script.
Is there also a script to uninstall ???
I see no --uninstall flag.

The thing is, i want to uninstall it. 

Thanks in advance.

**Comment by dceejay** [comment]
Sorry there is no default uninstall option.
To remove Node-RED - you can remove all the files  /usr/lib/node_modules/node-red*
and /usr/bin/node-red*
You may also want to remove any other node modules in /usr.lib/node_modules/

To remove nodejs - sudo apt purge nodejs
