### ISSUE TITLE
Script fails if sudo is last entry in group list

### ISSUE THREAD

**Issue by puni2k** [node-red/linux-installers#47]
Commit 7a61394 introduced a bug that would cause the script execution to fail on some systems if sudo is the last entry in the group list of the respective user

See my comment here:
[#r138923544](https://github.com/node-red/linux-installers/commit/7a61394cdb9e218bcc1f9a32901ed1c443650292#r138923544)

Two of my systems running Debian 11 (grep 3.6)  and 12 (grep 3.8) are affected by this, while another running Manjaro (grep 3.11) is not.

The following regex
```
^.*\bsudo\b.*
```
seems to work better on my systems. 
Not an expert on regexes though, so take it with a grain of salt.

**Comment by dceejay** [comment]
Thanks
