### ISSUE TITLE
During influxdb configuration, adding tokens cannot be synchronized with web pages. After the token is modified in the flows.json file, Web pages do not take effect

### ISSUE THREAD

**Issue by jiadong696** [node-red/linux-installers#51]
During influxdb configuration, adding tokens cannot be synchronized with web pages. After the token is modified in the flows.json file, Web pages do not take effect. 

![image](https://github.com/node-red/linux-installers/assets/149371204/f0788ab5-92fe-41f1-a8b8-6834c52443f3)
This profile, when loaded on the web page, cannot sync past tokens
![image](https://github.com/node-red/linux-installers/assets/149371204/e2997935-ca4b-446f-bed0-30e9a1f6174a)
![image](https://github.com/node-red/linux-installers/assets/149371204/126c07a1-787a-42dc-b141-631446df576e)
why is this???
Thank you for your answer!!!!

**Comment by knolleary** [comment]
Hi, this repository is for the Node-RED installer. It is not a support channel for general node-red questions.

Please use https://discourse.nodered.org for support questions.
