### ISSUE TITLE
Run the script without any questions?

### ISSUE THREAD

**Issue by TinajaLabs** [node-red/linux-installers#9]
Adding this to the case statement for the options makes the script a run unimpeded and automatable.  With this change, I can run this in ansible.

Change this:
```
      --confirm-pi)
        CONFIRM_PI="y"
        shift
        ;;
      --nodered-version=*)
        NODERED_VERSION="${1#*=}"
        shift
        ;;
```

to this:
```
      --confirm-pi)
        CONFIRM_PI="y"
        shift
        ;;
      --skip-pi)
        CONFIRM_PI="n"
        shift
        ;;
      --nodered-version=*)
        NODERED_VERSION="${1#*=}"
        shift
        ;;
```

Then you can execute the command to install on Ubuntu without questions with the following:

`$ ./update-nodejs-and-nodered --confirm-install --skip-pi`

Perhaps there's a better approach, but this works for me.

**Comment by dceejay** [comment]
Thanks - will add
